### PR TITLE
Fixes for OSX build

### PR DESCRIPTION
**Pull request by pyramation**
* properly bundles `boost` dylibs
* achieved by using `otool` and `install_name_tool` to create absolute paths wherever a `@loader_path` is referenced in boost libraries.

### CODE REVIEW

**Comment by pyramation** [comment]
also updates the dmg upon opening from this
screen shot 2018-01-21 at 7 28 39 pm

to this

screen shot 2018-01-21 at 6 58 07 pm

**Comment by pyramation** [comment]
Here's the latest build:

https://www.amazon.com/clouddrive/share/FgcnOhhqfF2aEBKLPngwmR0oGtr3pwJzMvofJiSievX

```
$ shasum SHIELD-Qt.dmg
06e00c385b3dee9c42616fd0fe50232ce0b540ee  SHIELD-Qt.dmg
```

**Comment by pyramation** [comment]
should close https://github.com/ShieldCoin/SHIELD/issues/24

**Comment by ShieldCoin** [comment]
That's great, thanks @pyramation , what's your address?

**Comment by pyramation** [comment]
Thanks @ShieldCoin ! appreciate it :) Happy to help, my address is Sj4DSMqgefw4XTP5zD3i8LNuhqQzgamvve

**Pull request merged**
